source "https://rubygems.org"

gem "jekyll", "~> 3.7.4"
gem "github-pages", "~> 192"
gem "jekyll-katex"
gem "jekyll-relative-links"
gem "jekyll-scholar"
gem "rake", "~> 12.3.1"
gem "slugify", "~> 1.0"
gem "tmpdir"